# ============================================================================
# Gradle Build Properties
# ============================================================================

# Java and Encoding
javaVersion=17

# CICS Configuration
cicsJvmServer=DFHWLP
cicsBomVersion=6.3-20250905155520

# Framework Versions
jakartaVersion=10.0.0
libertyApisVersion=25.0.0.9

# CICS Username and Password
cicsUser=XXX
cicsPass=XXX