// ============================================================================
// Root Project Configuration
// ============================================================================
rootProject.name = 'cics-java-liberty-springboot-kafka'

// ============================================================================
// Subprojects
// ============================================================================
include(':cics-java-liberty-springboot-kafka-app')
include(':cics-java-liberty-springboot-kafka-cicsbundle')

