// ============================================================================
// Root Project Configuration
// ============================================================================
rootProject.name = 'com.ibm.cicsdev.springboot.kafka'

// ============================================================================
// Subprojects
// ============================================================================
include(':com.ibm.cicsdev.springboot.kafka.app')
include(':com.ibm.cicsdev.springboot.kafka.bundle')

