
###############################################################################
# NOTE ON - VPN CONNECTIVITY
#
# When VPN is connected, the active interface is usually utunX or vpnX (e.g. utun4/vpn0).
# Example VPN IP:
#   ifconfig / ip addr show -> utun4 / vpn0 -> inet x.xx.xx.xxx
#
# Kafka bootstrap.servers must point to a broker address reachable via VPN.
spring.kafka.bootstrap-servers=x.x.x.x:9092

# Consumer group ID (unique per instance to process all messages, or shared name for shared processing)
spring.kafka.consumer.group-id=my-consumer-group

# Key and value deserializers
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Auto offset reset (optional)
spring.kafka.consumer.auto-offset-reset=earliest

# Commit & poll tuning (optional)
spring.kafka.listener.ack-mode=record
spring.kafka.listener.poll-timeout=3000

# This enables batch without custom bean:
spring.kafka.listener.type=batch

# Config to select which transaction id we want
cics.transaction.map.orders=ATC2
cics.transaction.map.test-topic=KAFK
