// ============================================================================
// Plugins
// ============================================================================
plugins {
    id 'com.ibm.cics.bundle' version '1.0.8'
}

// ============================================================================
// Project Information
// ============================================================================
description = 'CICS Kafka Springboot Application - CICS Bundle'
version = '1.0.0'

// ============================================================================
// Dependencies
// ============================================================================
dependencies {
    // Application WAR from sibling project
    cicsBundlePart project(path: ':com.ibm.cicsdev.springboot.kafka.app', configuration: 'archives')
}

// ============================================================================
// CICS Bundle Configuration
// ============================================================================
cicsBundle {
    build {
        defaultJVMServer = project.findProperty('cics.jvmserver') ?: cicsJvmServer
    }
    
    libertyWarUpload {
         serverUrl = 'http://<host>:<port>/com.ibm.cics.wlp.warupload/uploadApp'
         appId = 'cics-java-liberty-springboot-kafka'
         contextRoot = '/uploadApp'
         roleName = 'cics-user'
         userName = 'XXX'
         password = 'XXXX'
     }
}

